before_install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - yes | sudo apt-get install qtdeclarative5-dev
  - git submodule update --init --recursive
  - git submodule update --recursive  

script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make 
  - qmake -qt=qt5 utils/hevc_es_browser_gui/hevc_es_browser_gui.pro -r "CONFIG+=Release"
  - make
